// Uzbek (Latin) — default language. Keep the shape identical to ru.js (checked by `npm run check`).
export default {
  lang: "uz",
  htmlLang: "uz",
  ogLocale: "uz_UZ",
  short: "UZ",
  name: "O‘zbekcha",

  ui: {
    skip: "Asosiy matnga o‘tish",
    menu: "Menyu",
    closeMenu: "Menyuni yopish",
    mainNav: "Asosiy menyu",
    langNav: "Tilni tanlash",
    nav: { features: "Imkoniyatlar", how: "Qanday ishlaydi", pricing: "Narxlar va pilot", about: "Biz haqimizda" },
    cta: "Demo so‘rash",
    ctaSecondary: "Qanday ishlaydi?",
    download: "Yuklab olish",
    soon: "Tez orada",
    status: "Ishlab chiqilmoqda",
    more: "Batafsil",
    footer: {
      tagline: "Moy almashtirish shoxobchalari uchun rejalashtirilgan dastur. Guliston va Sirdaryodan boshlaymiz.",
      note: "Mytor hozir ishlab chiqilmoqda. Saytdagi barcha ekranlar interfeys namunasi, ulardagi ma’lumotlar esa xayoliy.",
      product: "Mahsulot",
      company: "Loyiha",
      privacy: "Maxfiylik siyosati",
      rights: "© 2026 Mytor",
    },
  },

  meta: {
    siteName: "Mytor",
    ogAlt: "Mytor: moy almashtirish shoxobchalari uchun dastur. 6 haftalik bepul pilot.",
    home: {
      title: "Mytor: moy almashtirish shoxobchalari uchun dastur",
      description: "Mashina tarixi, moy qoldig‘i va haydovchilarga Telegram eslatmalari bir joyda. Mytor ishlab chiqilmoqda: Guliston va Sirdaryoda 6 haftalik bepul pilot.",
    },
    features: {
      title: "Imkoniyatlar · Mytor",
      description: "Xizmat tarixi, raqam bo‘yicha qidiruv, moy kirimi va sarfi, sanoqdagi farqlar, Telegram eslatmalari, sodiqlik muhrlari, egasiga bildirishnomalar va ovozli kiritish.",
    },
    how: {
      title: "Qanday ishlaydi · Mytor",
      description: "Shoxobchani sozlashdan haydovchiga eslatmagacha: Mytor bilan bitta xizmat qanday yoziladi va egasi, usta hamda haydovchi nima oladi.",
    },
    pricing: {
      title: "Narxlar va pilot · Mytor",
      description: "Mytor 6 haftalik bepul pilot uchun birinchi shoxobchalarni qidirmoqda. Pilotdan keyingi narxlar hali sinovda: Start, Standart va Tarmoq.",
    },
    about: {
      title: "Biz haqimizda · Mytor",
      description: "Mytor nega yaratilmoqda, nega Guliston va Sirdaryodan boshlaymiz va shoxobchalarga qanday amaliy yordam berishni rejalashtiryapmiz.",
    },
    demo: {
      title: "Demo so‘rash · Mytor",
      description: "Mytor demosini so‘rang: bepul va hech narsaga majburlamaydi. Shoxobchangiz misolida ko‘rsatamiz va 6 haftalik bepul pilot haqida gaplashamiz.",
    },
    privacy: {
      title: "Maxfiylik siyosati · Mytor",
      description: "Mytor saytidagi so‘rov formasi orqali qanday ma’lumot yig‘iladi va u qanday ishlatiladi.",
    },
    notfound: {
      title: "Sahifa topilmadi · Mytor",
      description: "So‘ralgan sahifa topilmadi. Mytor saytining asosiy bo‘limlariga o‘ting.",
    },
  },

  // Shared fictional sample data used by previews on several pages.
  sample: {
    shop: "«Namuna» moy servisi",
    worker: "Sardor",
    worker2: "Ilhom",
    sum: "so‘m",
    car: "Chevrolet Spark",
  },

  phoneHero: {
    say: "«4 emas, 3 litr.»",
    card: "Xizmat yozuvi",
    rows: [
      ["Moy", "Lukoil Genesis 5W-30 · bochka"],
      ["Miqdor", "<s>4 L</s> 3 L"],
      ["Jami", "210 000 so‘m"],
      ["To‘lov", "Naqd · to‘langan"],
    ],
    stamp: "TASDIQLANDI · MYTOR · XIZMAT YOZILDI ·",
    ring: "MYTOR · XIZMAT DAFTARI · MOY HISOBI · GULISTON · SIRDARYO ·",
    history: "Spark tarixiga qo‘shildi",
    stock: "Qoldiq",
    notifyFrom: "Egasiga xabar",
    notifyText: "Yangi xizmat: 20 D 477 BB · Spark, 3 L, 210 000 so‘m",
  },

  demo: {
    region: "Ovozli kiritish namunasi",
    prev: "Orqaga",
    next: "Keyingi qadam",
    play: "Ketma-ket ko‘rsatish",
    pause: "To‘xtatish",
    restart: "Boshidan",
    stepWord: "qadam",
    newService: "Yangi xizmat",
    steps: [
      { title: "Usta gapiradi", text: "Usta tugmani bosib, xizmatni odatdagi so‘zlar bilan aytadi." },
      { title: "Qoralama to‘ldiriladi", text: "Mytor aytilganlarni maydonlarga joylaydi. Hali hech narsa saqlanmagan." },
      { title: "Noaniqlik aniqlanadi", text: "Ilova aniq mahsulotni so‘raydi, usta esa miqdorni tuzatadi: «4 emas, 3 litr.»" },
      { title: "Usta tasdiqlaydi", text: "Hamma maydon to‘g‘ri bo‘lsa, usta bitta tugma bilan tasdiqlaydi." },
      { title: "Tarix va qoldiq yangilanadi", text: "Xizmat mashina tarixiga yoziladi, moy qoldiqdan ayriladi, egasi xabar oladi." },
    ],
    listening: "Tinglanmoqda…",
    transcript: "«20 D 477 BB, Spark. Lukoil 5W-30, 4 litr, moy filtri bilan. 210 ming, naqd.»",
    draft: "Qoralama · saqlanmagan",
    fields: { vehicle: "Mashina", service: "Xizmat", product: "Moy", qty: "Miqdor", total: "Jami", payment: "To‘lov", mileage: "Probeg" },
    values: {
      vehicleFound: "bazadan topildi",
      service: "Motor moyi + moy filtri",
      productDraft: "Lukoil 5W-30",
      productFinal: "Lukoil Genesis 5W-30 · bochka",
      qtyDraft: "4 L",
      qtyFinal: "3 L",
      total: "210 000 so‘m",
      payment: "Naqd · to‘langan",
      optional: "ixtiyoriy",
    },
    needs: "aniqlash kerak",
    ask: "Lukoil 5W-30: bochkadanmi yoki butilkadan?",
    optBarrel: "Bochka",
    optBottle: "4 L butilka",
    correction: "«4 emas, 3 litr.»",
    corrected: "tuzatildi",
    confirm: "Tasdiqlash",
    confirmNote: "Tasdiqlashsiz hech narsa saqlanmaydi.",
    stamp: "TASDIQLANDI · MYTOR · XIZMAT YOZILDI ·",
    saved: "Saqlandi",
    history: "Spark tarixiga qo‘shildi",
    historyEntry: "Bugun · Lukoil Genesis 5W-30 · 3 L · moy filtri",
    stock: "Qoldiq · Lukoil Genesis 5W-30 (bochka)",
    stockFrom: "62,0 L",
    stockTo: "59,0 L",
    driverNote: "Haydovchining raqamli kitobchasi yangilanadi.",
    notifyFrom: "Mytor · egasi uchun",
    notifyTitle: "Yangi xizmat",
    notifyText: "20 D 477 BB · Spark. Lukoil Genesis 5W-30 (bochka), 3 L, moy filtri. 210 000 so‘m, naqd. Usta: Sardor.",
    time: "14:32",
  },

  home: {
    eyebrow: "Moy almashtirish shoxobchalari uchun · Guliston va Sirdaryo",
    title: "Mijoz qaytib keladi, <em>moy&nbsp;hisobi</em> aniq bo‘ladi.",
    lead: "Mytor moy almashtirish shoxobchalari uchun oddiy dastur. Usta xizmatni yozadi, Mytor esa mashina tarixini, moy qoldig‘ini va haydovchiga eslatmani o‘zi yuritadi.",

    bridge: {
      eyebrow: "Mytor nima qiladi",
      title: "Bitta yozuvdan uchta natija",
      lead: "Usta xizmatni bir marta yozib tasdiqlaydi. Qolganini Mytor o‘zi yangilaydi.",
      link: "Bosqichma-bosqich: qanday ishlaydi",
      recordTitle: "Tasdiqlangan xizmat",
      record: [
        ["Mashina", "Chevrolet Spark"],
        ["Xizmat", "Motor moyi + moy filtri"],
        ["Moy", "Lukoil Genesis 5W-30 · 3 L"],
        ["Jami", "210 000 so‘m · naqd"],
      ],
      outcomes: [
        { title: "Mashina tarixi", why: "Keyingi safar usta nima quyilganini biladi. Haydovchi buni qadrlaydi va qaytib keladi." },
        { title: "Moy qoldig‘i", why: "Sarf qoldiqdan avtomatik ayriladi. Sanoqda farq chiqsa, darhol ko‘rasiz." },
        { title: "Xabarlar", why: "Siz xizmat haqida bilib turasiz, haydovchiga esa keyingi almashtirish vaqtida eslatma boradi." },
      ],
      timeline: [
        ["Bugun", "Lukoil Genesis 5W-30 · 3 L"],
        ["18-may", "Lukoil Genesis 5W-30 · 3 L"],
        ["3-mart", "Karobka: Dexron VI · 2 L"],
      ],
      ownerMsg: "Egasiga: yangi xizmat, 210 000 so‘m",
      driverMsg: "Haydovchiga: keyingi almashtirish vaqtida eslatma",
    },

    problems: {
      eyebrow: "Muammo",
      title: "Pul ko‘pincha ikki joyda yo‘qoladi",
      lead: "Hisob daftarda yoki ustaning xotirasida tursa, shunday bo‘ladi:",
      items: [
        {
          tag: "Mijozlar",
          title: "Mijoz qaytib kelmaydi",
          text: "Haydovchi qachon va qaysi moy quyilganini eslamaydi. Daftarcha yo‘qoladi, eslatma bo‘lmaydi. Keyingi safar u boshqa shoxobchaga kirib qoladi.",
          list: ["Kim, qaysi mashina, qaysi moy: hech biri yozilmagan", "Keyingi almashtirish vaqtini hech kim eslatmaydi", "Qog‘oz sodiqlik kartalari yo‘qoladi"],
        },
        {
          tag: "Moy qoldig‘i",
          title: "Moy qayerga ketganini bilish qiyin",
          text: "Moy bochkadan litrlab va butilkada sotiladi. Kirim, sarf va qolgan miqdorni solishtirish uchun tayyor hisob yo‘q.",
          list: ["Kirim va sarf alohida yoziladi yoki umuman yozilmaydi", "Sanoqda farq chiqsa, sababini topish qiyin", "Egasi har kuni joyida bo‘la olmaydi"],
        },
      ],
    },

    voice: {
      eyebrow: "Ovozli kiritish",
      title: "Usta gapiradi, Mytor yozuvni tayyorlaydi",
      lead: "Qo‘li moyli ustaga telefonda forma to‘ldirish noqulay. Usta xizmatni aytadi, Mytor qoralamani to‘ldiradi, usta tekshirib tasdiqlaydi.",
    },

    benefits: {
      eyebrow: "Foyda",
      title: "Egasi uchun eng muhimi",
      link: "Barcha imkoniyatlar",
      big: {
        title: "Mijozlar qaytib kelishi uchun sabab",
        text: "Har bir haydovchining tarixi saqlanadi, keyingi almashtirish vaqtida esa unga Telegram orqali eslatma boradi. Sodiqlik muhrlari ham raqamli bo‘ladi va yo‘qolmaydi.",
        stampsLabel: "Sodiqlik muhrlari: 6 tadan 4 tasi",
      },
      items: [
        { sample: "62,0 L → 59,0 L", title: "Moy hisobi litrgacha", text: "Kirim, sarf va sanoq bir joyda. Farq chiqsa, uni ko‘rasiz va sababini aniqlaysiz." },
        { sample: "14:32 · Yangi xizmat", title: "Joyida bo‘lmasangiz ham xabardor", text: "Xizmatlar, kam qolgan moy, sanoqdagi farqlar va tuzatishlar haqida bildirishnoma. Xohlasangiz, kunlik qisqa xulosa ham." },
        { sample: "«4 emas, 3 litr.»", title: "Usta uchun tez", text: "Raqam bo‘yicha qidiruv va ovozli kiritish. Yozuv ishni sekinlashtirmasligi kerak." },
      ],
    },

    support: {
      eyebrow: "Pilot",
      title: "6 hafta bepul pilot: kelib, joyida sozlab beramiz",
      lead: "Mytor hali ishlab chiqilmoqda, shuning uchun uni birinchi shoxobchalar bilan birga sinaymiz. Pilot bepul, to‘lov ma’lumotlari so‘ralmaydi, davom etish yoki to‘xtatishni o‘zingiz hal qilasiz.",
      link: "Pilot va narxlar",
      steps: [
        ["Tanishuv", "Shoxobchangizga kelamiz yoki qo‘ng‘iroq qilamiz va qanday ishlayotganingizni tushunamiz."],
        ["Sozlash", "Moy turlari, butilka hajmlari, narxlar va ustalar ro‘yxatini birga kiritamiz."],
        ["O‘rgatish", "Ustalarga ish joyida ko‘rsatamiz: mashinani topish, xizmatni yozish, tasdiqlash."],
        ["Aloqada bo‘lish", "Pilot davomida muntazam bog‘lanib, savol va takliflaringizni yig‘amiz."],
      ],
    },

    faq: {
      eyebrow: "Savollar",
      title: "Ko‘p beriladigan savollar",
      items: [
        { q: "Mytor allaqachon ishlayaptimi?", a: "Yo‘q. Mytor hozir ishlab chiqilmoqda. Saytdagi barcha ekranlar interfeys namunalari. Biz bir nechta shoxobcha bilan birga pilot o‘tkazishni rejalashtiryapmiz." },
        { q: "Demo so‘rasam, sotib olishim shartmi?", a: "Yo‘q. Demo bepul va hech narsaga majburlamaydi. Ko‘rib chiqasiz, savollaringizni berasiz, keyin pilotga qo‘shilish yoki qo‘shilmaslikni o‘zingiz hal qilasiz." },
        { q: "Pilot qancha turadi?", a: "Taklifimiz: 6 hafta, bepul. Saytda to‘lov qabul qilinmaydi. Pilotdan keyingi narxlar hali sinovda va pilot ishtirokchilari bilan birga belgilanadi." },
        { q: "Telefonga alohida ilova o‘rnatish kerakmi?", a: "Birinchi versiya telefon va kompyuter brauzerida ochiladigan veb-ilova sifatida rejalashtirilgan. Haydovchilarga eslatmalar Telegram orqali boradi." },
        { q: "Ustalarim texnikaga unchalik qiziqmaydi. Ular uddalay oladimi?", a: "Mytor shu sababli oddiy qilib loyihalanmoqda: raqam bo‘yicha qidiruv, ovozli kiritish va bitta tasdiqlash tugmasi. Sozlash va o‘rgatishni joyida o‘zimiz qilamiz." },
        { q: "Qoldiqda farq chiqsa, demak, kimdir o‘g‘irlaganmi?", a: "Shart emas. Farqning sababi yozilmay qolgan xizmat, to‘kilish yoki noto‘g‘ri sanoq bo‘lishi mumkin. Mytor farqni ko‘rsatadi va tuzatishlarni qayd etadi, xulosani esa siz chiqarasiz." },
        { q: "Haydovchilarning ma’lumotlari-chi?", a: "Telegram xabarlari faqat haydovchining roziligi bilan yuborilishi rejalashtirilgan. Ma’lumotlarni himoya qilish va qonun talablariga muvofiqlik ishga tushirishdan oldin tekshiriladi." },
      ],
    },
  },

  cta: {
    title: "Shoxobchangizda qanday ishlashini ko‘rmoqchimisiz?",
    text: "Qisqa so‘rov qoldiring, qo‘ng‘iroq qilib, demo uchun qulay vaqtni kelishamiz. Bepul va majburiyatsiz.",
  },

  features: {
    eyebrow: "Imkoniyatlar",
    title: "Mytor shoxobchada nima qiladi",
    lead: "Usta uchun tez yozuv, egasi uchun moy hisobi, haydovchi uchun eslatma. Ekranlar namuna, ma’lumotlar xayoliy.",
    toc: "Bo‘limlar",
    tocItems: ["Xizmat tarixi", "Ovozli kiritish", "Moy hisobi", "Egasiga xabarlar", "Telegram va muhrlar"],

    records: {
      eyebrow: "01 · Mijoz va mashina tarixi",
      title: "Mijozni taniysiz, oldingi xizmat bir qarashda ko‘rinadi",
      lead: "Mijoz kelganda raqamini yoki telefonini kiriting: oldingi xizmatlar, quyilgan moy va probeg ochiladi.",
      points: [
        "Motor moyi va karobka moyi alohida yoziladi",
        "Aniq mahsulot, miqdor, sana va kerak bo‘lsa probeg",
        "Almashtirilgan filtrlar",
        "Xizmatni qaysi usta bajargani",
      ],
      example: "Haydovchi «O‘tgan safar qaysi moy quygan edingiz?» deb so‘rasa, javob raqamni yozishingiz bilan ko‘rinadi.",
      lookupLabel: "Raqam, telefon yoki mashina",
      lookupPlaceholder: "Masalan: 477",
      lookupHint: "Sinab ko‘ring: «477», «Cobalt» yoki «93»",
      lookupEmpty: "Hech narsa topilmadi. Namuna ro‘yxatida 4 ta xayoliy mashina bor.",
      lookupCount: "Topildi:",
      cars: [
        { plate: "20 D 477 BB", model: "Chevrolet Spark", who: "Malika opa", phone: "+998 90 ••• •• 14", search: "20d477bb spark malika 99890", last: "12-sentabr · Lukoil Genesis 5W-30 · 3 L" },
        { plate: "20 A 257 BA", model: "Chevrolet Cobalt", who: "Jasur aka", phone: "+998 93 ••• •• 52", search: "20a257ba cobalt jasur 99893", last: "3-sentabr · ZIC X5 10W-40 · 4 L" },
        { plate: "20 E 330 MA", model: "Chevrolet Gentra", who: "Bobur aka", phone: "+998 91 ••• •• 07", search: "20e330ma gentra bobur 99891", last: "21-avgust · Total Quartz 5W-40 · 4,5 L" },
        { plate: "20 H 051 CA", model: "BYD Song Plus", who: "Kamola opa", phone: "+998 97 ••• •• 63", search: "20h051ca byd song kamola 99897", last: "30-iyun · Shell Helix 5W-40 · 4 L" },
      ],
      historyTitle: "Xizmat tarixi · 20 D 477 BB",
      history: [
        { date: "12-sentabr 2026", kind: "Motor moyi", text: "Lukoil Genesis 5W-30 · 3 L · moy filtri", km: "61 400 km" },
        { date: "18-may 2026", kind: "Motor moyi", text: "Lukoil Genesis 5W-30 · 3 L", km: "57 900 km" },
        { date: "3-mart 2026", kind: "Karobka moyi", text: "Dexron VI · 2 L", km: "" },
      ],
    },

    stock: {
      eyebrow: "03 · Moy qoldig‘i: kirim, sarf, sanoq",
      title: "Moy qayerga ketganini ko‘rasiz",
      lead: "Bochkadagi moy litrda, butilkadagi moy donada hisoblanadi. Yetkazib berilgan moy qoldiqqa qo‘shiladi, har bir tasdiqlangan xizmat esa uni avtomatik ayiradi. Siz sanaysiz, Mytor solishtiradi.",
      caution: {
        title: "Farq nimani anglatadi?",
        text: "Farq tekshirish uchun signal, ayblov emas. Sababi yozilmay qolgan xizmat, to‘kilish, o‘lchash xatosi yoki noto‘g‘ri kiritilgan miqdor bo‘lishi mumkin. Egasi sababini aniqlaydi; tuzatish kiritilsa, u ham tarixda saqlanadi.",
      },
    },

    recon: {
      title: "Sanoq · Lukoil Genesis 5W-30 (bochka)",
      rows: [
        ["Oxirgi sanoq", "38,0 L"],
        ["Kirim", "+200,0 L"],
        ["Yozilgan sarf · 52 xizmat", "−176,0 L"],
      ],
      expected: "Kutilgan qoldiq",
      expectedVal: "62,0 L",
      counted: "Sanalgan",
      countedVal: "55,0 L",
      gap: "Farq",
      gapVal: "−7,0 L",
      gapNote: "tekshirib ko‘ring",
      gaugeLabel: "Kutilgan qoldiq 62 litr, sanalgan 55 litr, farq 7 litr",
      bottle: "ZIC X5 10W-40 · 4 L butilka: kutilgan 9 dona, sanalgan 9 dona, mos",
      note: "Farq o‘g‘irlik isboti emas. Mytor faqat qayerga qarash kerakligini ko‘rsatadi.",
    },

    telegram: {
      eyebrow: "05 · Telegram, servis kitobcha, muhrlar",
      title: "Haydovchi o‘z vaqtida qaytib keladi",
      lead: "Eslatma, raqamli servis kitobcha va sodiqlik muhrlari Telegram orqali keladi. Haydovchiga hech narsa o‘rnatish shart emas.",
      points: [
        { t: "Eslatma", d: "Keyingi almashtirish vaqti yaqinlashganda qisqa xabar." },
        { t: "Raqamli servis kitobcha", d: "Har bir almashtirish: sana, moy, miqdor va probeg. Qog‘oz daftarcha yo‘qolsa ham tarix saqlanadi." },
        { t: "Sodiqlik muhrlari", d: "Har bir xizmat uchun bitta muhr. Nechta muhrdan keyin qanday chegirma berishni shoxobcha o‘zi belgilaydi." },
      ],
      bot: "Mytor bot",
      botSub: "«Namuna» moy servisi",
      msg1: "Assalomu alaykum, Jasur aka! Chevrolet Cobalt moyini almashtirish vaqti yaqinlashdi.",
      msg1b: "Oxirgi marta: 3-sentabr, ZIC X5 10W-40, 4 L.",
      bookTitle: "Servis kitobcha · 20 A 257 BA",
      book: [
        ["3-sentabr", "ZIC X5 10W-40 · 4 L"],
        ["28-iyun", "ZIC X5 10W-40 · 4 L · havo filtri"],
        ["9-aprel", "ZIC X5 10W-40 · 4 L"],
      ],
      stampsTitle: "Sodiqlik muhrlari",
      stampsLabel: "6 tadan 4 ta muhr",
      reply: "Rahmat, shanba kuni boraman",
      time1: "10:00",
      time2: "10:14",
    },

    owner: {
      eyebrow: "04 · Egasiga xabarlar va kunlik xulosa",
      title: "Shoxobchada bo‘lmasangiz ham xabardor",
      lead: "Yangi xizmat, kam qolgan moy, sanoqdagi farq va har bir tuzatish haqida Telegram orqali xabar olasiz. Qaysi xabarlar kelishini o‘zingiz tanlaysiz; kun oxirida qisqa xulosa ham olishingiz mumkin.",
      feedTitle: "Egasi uchun xabarlar",
      feed: [
        { k: "service", time: "14:32", t: "Yangi xizmat", d: "20 D 477 BB · Spark. Lukoil Genesis 5W-30 (bochka), 3 L. 210 000 so‘m, naqd. Usta: Sardor." },
        { k: "low", time: "15:10", t: "Moy kam qoldi", d: "Mobil Super 10W-40: 12 L qoldi (minimum 20 L)." },
        { k: "fix", time: "17:45", t: "Tuzatish", d: "20 E 330 MA yozuvida miqdor 4,5 L dan 4 L ga o‘zgartirildi. Usta: Ilhom." },
        { k: "gap", time: "18:05", t: "Sanoqda farq", d: "Lukoil Genesis 5W-30: kutilgan 62 L, sanalgan 55 L (−7 L). Tekshirib ko‘ring." },
        { k: "daily", time: "20:00", t: "Kunlik xulosa", d: "14 ta xizmat · 2 870 000 so‘m · 46,5 L moy." },
      ],
    },

    voice: {
      eyebrow: "02 · Ovozli kiritish",
      title: "Qo‘li band usta ham yozuvni to‘liq qiladi",
      lead: "Usta xizmatni oddiy so‘zlar bilan aytadi. Mytor qoralama tayyorlaydi, aniq bo‘lmagan joyni so‘raydi, usta tasdiqlagandan keyingina yozuv saqlanadi.",
      langNote: "O‘zbek va rus tillarida gapirish rejalashtirilgan. Ovoz bilan qulay bo‘lmasa, usta qo‘lda ham kiritishi mumkin.",
    },
  },

  how: {
    eyebrow: "Qanday ishlaydi",
    title: "Sozlashdan eslatmagacha",
    lead: "Usta odatdagidek ishlaydi: mashinani topadi, xizmatni aytadi, tasdiqlaydi. Qolganini Mytor o‘zi qiladi.",
    groups: ["Bir marta · sozlash", "Har bir mashinada · usta", "Tasdiqlangandan keyin · Mytor o‘zi"],
    fan: {
      title: "Usta tasdiqladi",
      record: "Lukoil Genesis 5W-30 · 3 L · 210 000 so‘m",
      note: "Shu bitta yozuvdan to‘rtta natija",
    },
    now: "Shu zahoti",
    delta: "−3,0 L",
    later: "Keyinroq",
    stages: [
      {
        title: "Shoxobcha sozlanadi",
        text: "Moy mahsulotlari (bochka va butilka), narxlar, ustalar va boshlang‘ich qoldiq kiritiladi. Buni birinchi tashrifda birga qilamiz.",
        list: ["Moy turlari va butilka hajmlari", "Boshlang‘ich qoldiq sanog‘i", "Ustalar ro‘yxati", "Egasi qaysi xabarlarni olishi"],
      },
      {
        title: "Mijoz va mashina topiladi",
        text: "Usta raqam yoki telefonni kiritadi. Doimiy mijozning tarixi va oxirgi quyilgan moyi darhol ko‘rinadi; yangi mijoz bir marta qo‘shiladi.",
        list: [],
      },
      {
        title: "Xizmat yoziladi",
        text: "Usta xizmatni ovoz bilan aytadi yoki qo‘lda kiritadi: mashina, xizmat turi, moy, miqdor, summa va to‘lov.",
        list: [],
      },
      {
        title: "Tafsilotlar tasdiqlanadi",
        text: "Mytor noaniq joyni so‘raydi, usta xatoni tuzatadi va tasdiqlaydi. Tasdiqlashsiz hech narsa saqlanmaydi.",
        list: [],
      },
      {
        title: "Xizmat tarixi yangilanadi",
        text: "Xizmat mashina tarixiga yoziladi. Keyingi safar usta oldingi moyni va miqdorni ko‘radi.",
        list: [],
      },
      {
        title: "Moy qoldig‘i yangilanadi",
        text: "Sarflangan moy qoldiqdan ayriladi. Keyingi sanoqda qoldiq hisob bilan solishtiriladi.",
        list: [],
      },
      {
        title: "Egasiga xabar boradi",
        text: "Egasi xizmat haqida bildirishnoma oladi. Kam qolgan moy, sanoqdagi farq va tuzatishlar haqida ham.",
        list: [],
      },
      {
        title: "Haydovchiga keyinroq eslatiladi",
        text: "Haydovchining raqamli kitobchasi yangilanadi. Keyingi almashtirish vaqti yaqinlashganda Telegram’da eslatma boradi.",
        list: [],
      },
    ],
    stageWord: "Bosqich",
    roles: {
      eyebrow: "Kim nima oladi",
      title: "Har kim o‘z foydasini ko‘radi",
      items: [
        { k: "owner", title: "Egasi", lead: "Nazorat va qaytib keladigan mijozlar", list: ["Har bir xizmat va to‘lov yozuvda", "Moy qoldig‘i va farqlar ko‘rinib turadi", "Joyida bo‘lmasa ham bildirishnomalar", "Eslatmalar orqali mijozlarni qaytarish"] },
        { k: "worker", title: "Usta", lead: "Kamroq qog‘oz, tezroq yozuv", list: ["Raqam bo‘yicha qidiruv", "Ovoz bilan yoki qo‘lda kiritish", "Xatoni tasdiqlashdan oldin tuzatish", "Doimiy mijozning oldingi moyi ko‘rinadi"] },
        { k: "driver", title: "Haydovchi", lead: "Eslab yurish shart emas", list: ["Telegram’da eslatma", "Raqamli servis kitobcha", "Sodiqlik muhrlari", "Ilova o‘rnatish shart emas"] },
      ],
    },
    pilot: {
      title: "Shoxobchangizda 6 hafta bepul sinab ko‘ring",
      text: "Pilot qanday o‘tishini va sinovdagi narxlarni ko‘ring.",
      link: "Narxlar va pilot",
    },
  },

  pricing: {
    eyebrow: "Narxlar va pilot",
    title: "Avval 6 hafta bepul sinab ko‘ring",
    lead: "Mytor hali ishlab chiqilmoqda va biz birinchi pilot shoxobchalarini qidiryapmiz. Pilotda Mytor’ni oddiy ish kuningizda birga sinaymiz. Pilot bepul, to‘lov olinmaydi.",
    facts: ["6 hafta", "Bepul", "Majburiyatsiz"],
    ctaNote: "Demo so‘rash sizni pilotga yoki xaridga majburlamaydi.",
    proposal: "Narxlar sinovda · hali yakuniy emas",
    pilotTitle: "Pilot qanday o‘tadi",
    weeks: [
      { w: "1-hafta", t: "Sozlash va o‘rgatish", d: "Moy turlari, qoldiq va ustalar kiritiladi, ustalar joyida o‘rgatiladi." },
      { w: "2–5-hafta", t: "Kundalik ish", d: "Ustalar xizmatlarni yozadi, siz bildirishnomalar olasiz. Muntazam aloqada bo‘lamiz." },
      { w: "6-hafta", t: "Natijani ko‘rib chiqish", d: "Nima foydali bo‘ldi, nimani o‘zgartirish kerak, birga muhokama qilamiz. Davom etish yoki to‘xtatish sizning qaroringiz." },
    ],
    plansTitle: "Pilotdan keyin: sinovdagi narxlar",
    plansLead: "Bu narxlarni pilot ishtirokchilari bilan muhokama qilib, keyin tasdiqlaymiz. Har bir rejaga nimalar kirishi ham pilotda aniqlanadi.",
    planTag: "Sinov uchun taklif",
    forWord: "Kim uchun",
    plans: [
      { name: "Start", price: "99 000", unit: "so‘m / oy", for: "Bitta kichik shoxobcha" },
      { name: "Standart", price: "199 000", unit: "so‘m / oy", for: "Bitta serqatnov shoxobcha" },
      { name: "Tarmoq", price: "149 000", unit: "so‘m / oy · har bir nuqta", for: "3 va undan ortiq nuqtasi bor egalar" },
    ],
    noPay: "Saytda to‘lov qabul qilinmaydi va karta ma’lumotlari so‘ralmaydi.",
    faqTitle: "Narx va pilot bo‘yicha savollar",
    faq: [
      { q: "Demo so‘rasam, sotib olishim shartmi?", a: "Yo‘q. Demo bepul va hech narsaga majburlamaydi. Pilotga qo‘shilish yoki qo‘shilmaslikni demodan keyin o‘zingiz hal qilasiz." },
      { q: "Pilotdan keyin to‘lov avtomatik boshlanadimi?", a: "Yo‘q. Avtomatik to‘lov yo‘q. Davom etishni xohlasangiz, shartlarni alohida kelishib olamiz." },
      { q: "Nega narxlar «sinovda» deb yozilgan?", a: "Mytor hali ishga tushmagan. Narx shoxobcha egalari uchun adolatli bo‘lishi kerak, shuning uchun uni pilot ishtirokchilari bilan tekshiramiz." },
      { q: "Pilotda kim qatnasha oladi?", a: "Avvalo Guliston va Sirdaryo viloyatidagi moy almashtirish shoxobchalari. Boshqa shahardan bo‘lsangiz ham so‘rov qoldiring." },
      { q: "Bir nechta shoxobcham bor. Mytor mos keladimi?", a: "3 va undan ortiq nuqta uchun alohida «Tarmoq» narxi sinovda. So‘rovda shoxobchalar sonini belgilang." },
      { q: "Haydovchilar to‘laydimi?", a: "Yo‘q. Rejaga ko‘ra, haydovchilar uchun Mytor bepul." },
    ],
  },

  about: {
    eyebrow: "Biz haqimizda",
    title: "Mytor nega yaratilmoqda",
    lead: "Moy almashtirish oddiy, lekin har kuni takrorlanadigan ish. Biz uning hisobini ham oddiy qilmoqchimiz.",
    why: {
      title: "Muammo daftarda",
      paras: [
        "Ko‘p shoxobchalarda mijozlar va moy hisobi daftarda, ba’zan esa faqat ustaning xotirasida turadi. Haydovchiga berilgan servis daftarchasi bir-ikki tashrifdan keyin yo‘qoladi. Egasi esa moy qayerga sarflanganini aniq bilishga qiynaladi.",
        "Umumiy avtoservis dasturlarida imkoniyat ko‘p, lekin moy almashtirish shoxobchasi uchun ular ortiqcha murakkab bo‘lishi mumkin. Mytor aynan moy almashtirish ishiga moslab yaratilmoqda.",
      ],
    },
    local: {
      title: "Guliston va Sirdaryodan boshlaymiz",
      text: "Kichik hududdan boshlash shoxobchalarga borish, egalari va ustalari bilan gaplashish hamda mahsulotni ular bilan birga shakllantirish imkonini beradi.",
      list: ["Interfeys o‘zbek (lotin) va rus tillarida", "To‘lov usuli yozuvda qayd etiladi: naqd, karta, Click yoki Payme", "Haydovchilar allaqachon ishlatadigan Telegram"],
    },
    support: {
      title: "Amaliy yordam",
      text: "Dasturni o‘rnatib, ketib qolish yetarli emas. Rejamiz: sozlashni joyida qilish, ustalarni ish joyida o‘rgatish va pilot davomida aloqada bo‘lish.",
    },
    principles: {
      title: "Nimaga e’tibor beramiz",
      items: [
        { t: "Halollik", d: "Mytor hali ishlab chiqilmoqda va biz buni yashirmaymiz. Saytdagi ekranlar faqat namuna." },
        { t: "Adolatli nazorat", d: "Qoldiqdagi farq tekshirish uchun signal, ayb emas. Tuzatishlar ham ochiq qayd etiladi." },
        { t: "Ma’lumotga hurmat", d: "Haydovchilarga xabarlar roziligi bilan yuboriladi. Ma’lumotlar faqat xizmat uchun ishlatiladi." },
        { t: "Oddiylik", d: "Usta uchun har bir ortiqcha bosish muammo. Keraksiz narsani qo‘shmaymiz." },
      ],
    },
    status: {
      title: "Hozirgi holat",
      text: "Mytor rejalashtirilgan dastur, hali ishga tushmagan. Birinchi pilot shoxobchalarini qidiryapmiz. Alohida smartfon ilovasi hozircha yo‘q.",
    },
  },

  form: {
    eyebrow: "Demo so‘rash",
    title: "Mytor’ni shoxobchangiz misolida ko‘ring",
    lead: "Ismingiz va telefoningizni qoldiring, qo‘ng‘iroq qilib, qulay vaqtni kelishamiz. Demoda ishlab chiqilayotgan Mytor’ni ko‘rsatamiz va 6 haftalik bepul pilot haqida gaplashamiz.",
    facts: ["Bepul", "Majburiyatsiz", "O‘zbek yoki rus tilida"],
    legend: "So‘rov ma’lumotlari",
    requiredNote: "* bilan belgilangan maydonlar majburiy",
    name: "Ismingiz",
    shop: "Shoxobcha nomi",
    city: "Shahar yoki tuman",
    cityHint: "Masalan: Guliston",
    phone: "Telefon raqami",
    phoneHint: "Masalan: +998 90 123 45 67",
    branches: "Nechta shoxobchangiz bor?",
    branchOptions: [["1", "1 ta"], ["2", "2 ta"], ["3+", "3 va undan ko‘p"]],
    note: "Izoh",
    noteHint: "Masalan: qo‘ng‘iroq uchun qulay vaqt yoki savolingiz",
    optional: "ixtiyoriy",
    consent: "Ma’lumotlarimdan ushbu so‘rov bo‘yicha men bilan bog‘lanish uchun foydalanishingizga roziman.",
    consentMore: "Maxfiylik siyosati",
    submit: "Demo so‘rash",
    sending: "Yuborilmoqda…",
    cities: ["Guliston", "Sirdaryo", "Yangiyer", "Shirin", "Boyovut", "Xovos", "Sardoba", "Oqoltin", "Mirzaobod", "Sayxunobod"],
    errors: {
      required: "Bu maydonni to‘ldiring.",
      phone: "Telefon raqamini to‘liq kiriting, masalan +998 90 123 45 67.",
      consent: "Davom etish uchun roziligingizni belgilang.",
      summary: "Iltimos, belgilangan maydonlarni tekshiring.",
    },
    notConnectedBanner: "Diqqat: so‘rov formasi hali serverga ulanmagan. Shaklni to‘ldirib ko‘rishingiz mumkin, lekin so‘rov hech qayerga yuborilmaydi.",
    notConnectedTitle: "So‘rov yuborilmadi",
    notConnectedText: "Bu sayt hozircha so‘rovlarni qabul qiladigan serverga ulanmagan. Ma’lumotlaringiz hech qayerga yuborilmadi va saqlanmadi.",
    successTitle: "Rahmat! So‘rovingiz bizga yetib keldi",
    successText: "Demo uchun qulay vaqtni kelishish maqsadida siz qoldirgan raqamga qo‘ng‘iroq qilamiz.",
    failTitle: "So‘rovni yuborib bo‘lmadi",
    failText: "Kiritgan ma’lumotlaringiz shaklda saqlanib qoldi. Internet aloqasini tekshirib, «Demo so‘rash» tugmasini yana bosing.",
    next: {
      title: "Keyin nima bo‘ladi?",
      steps: ["So‘rovingizni ko‘rib chiqamiz.", "Qulay vaqtni kelishish uchun telefon qilamiz.", "Demoni shoxobchangizda yoki onlayn ko‘rsatamiz."],
      note: "Demo va 6 haftalik pilot bepul. To‘lov yoki karta ma’lumotlari so‘ralmaydi, davom etish o‘zingizning qaroringiz.",
    },
  },

  privacy: {
    eyebrow: "Huquqiy ma’lumot",
    title: "Maxfiylik siyosati",
    updated: "Yangilangan sana: 2026-yil 7-oktabr",
    draftNote: "Bu dastlabki matn. Mytor ishga tushirilishidan oldin u yuridik jihatdan tekshiriladi va yangilanadi.",
    sections: [
      { h: "Qanday ma’lumot yig‘amiz", p: "Demo yoki pilot so‘rovi formasida siz kiritgan ma’lumotlar: ism, telefon raqami, shahar yoki tuman, shuningdek ixtiyoriy ravishda shoxobcha nomi, shoxobchalar soni va izoh." },
      { h: "Ma’lumotlar qayerga boradi", p: "Hozircha forma hech qanday serverga ulanmagan: saytda to‘ldirilgan ma’lumotlar yuborilmaydi va saqlanmaydi. Forma ulanganidan keyin bu yerda so‘rovlar qayerda saqlanishi va ularni kim ko‘rishi aniq yoziladi." },
      { h: "Nima uchun ishlatamiz", p: "Faqat so‘rovingiz bo‘yicha siz bilan bog‘lanish hamda demo yoki pilotni tashkil qilish uchun. Ma’lumotlaringizni sotmaymiz va reklama tarqatish uchun ishlatmaymiz." },
      { h: "Qancha saqlaymiz", p: "So‘rov ko‘rib chiqilib, siz bilan muloqot yakunlangunga qadar. Pilotga qo‘shilmasangiz, ma’lumotlaringizni o‘chirishni so‘rashingiz mumkin." },
      { h: "Cookie va kuzatuv", p: "Bu sayt cookie-fayllar va analitika vositalaridan foydalanmaydi. Tanlagan tilingiz faqat brauzeringizning o‘zida eslab qolinadi va bizga yuborilmaydi. Shriftlar Google Fonts xizmatidan yuklanadi, shu sababli brauzeringiz Google serverlariga murojaat qiladi." },
      { h: "Haydovchilar ma’lumotlari", p: "Mytor ishga tushganda haydovchilarning telefon raqami va mashina ma’lumotlari faqat xizmat tarixi va eslatmalar uchun ishlatilishi rejalashtirilgan. Telegram xabarlari haydovchining roziligi bilan yuboriladi va istalgan vaqtda o‘chirib qo‘yilishi mumkin." },
      { h: "Sizning huquqlaringiz", p: "O‘zingiz haqingizdagi ma’lumotlarni ko‘rish, tuzatish yoki o‘chirishni so‘rashingiz mumkin. Buni siz bilan bog‘langanimizda ayting." },
      { h: "Qonunchilik", p: "Ma’lumotlarni qayta ishlashning O‘zbekiston Respublikasining «Shaxsga doir ma’lumotlar to‘g‘risida»gi Qonuniga muvofiqligi ishga tushirishdan oldin tekshiriladi." },
    ],
  },

  notfound: {
    code: "404",
    title: "Bu sahifa topilmadi",
    text: "Havola eskirgan yoki manzilda xato bo‘lishi mumkin. Quyidagi bo‘limlardan birini tanlang.",
    stamp: "TOPILMADI · 404 · MYTOR ·",
    links: {
      home: "Bosh sahifa: Mytor nima va kimlar uchun",
      features: "Imkoniyatlar: tarix, moy hisobi, Telegram, ovozli kiritish",
      how: "Qanday ishlaydi: bitta xizmat boshidan oxirigacha",
      pricing: "Narxlar va pilot: 6 hafta bepul sinov taklifi",
      demo: "Demo so‘rash: so‘rov qoldirish",
    },
    other: "Русская версия сайта",
  },
};
